Las personas solicitantes deberán aportar junto con el anexo I los anexos II y III y la siguiente documentación:
Copia compulsada del pasaporte, si procede, relativa a la persona solicitante y, en su caso, a la que la acompaña: cónyuge, pareja de hecho o relación análoga a la conyugal, hija o hijo con discapacidad o otra persona.
Copia del libro de familia de la persona solicitante en el caso de que quiera acudir al programa acompañada de un hijo o hija con discapacidad.
Certificado del grado de discapacidad del hijo o hija de la persona solicitante, si dicho certificado no fuera expedido por la Xunta de Galicia o no estuviera en poder de ésta.
Certificado de las pensiones non otorgadas por el INSS ni por la Xunta de Galicia, de la persona solicitante y de la acompañante, en su caso.
Las solicitudes se presentarán preferiblemente por vía electrónica a través del formulario normalizado disponible en la sede electrónica de la Xunta de Galicia, https://sede.xunta.gal.
Opcionalmente, se podrán presentar las solicitudes presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
Para la presentación de las solicitudes se podrá emplear cualquiera de los mecanismos de identificación y firma admitidos por la sede electrónica de la Xunta de Galicia, incluido el sistema de usuario y clave Chave365 (https://sede.xunta.gal/chave365).
En cada solicitud sólo se podrá relacionar un máximo de tres destinos por orden de prioridad.
No será necesario aportar los documentos que ya fueran presentados anteriormente.
A estos efectos, la persona interesada deberá indicar en que momento y ante que órgano administrativo presentó los citados documentos.
Se presumirá que esta consulta es autorizada por las personas interesadas, salvo que conste en el procedimiento su oposición expresa.
En los supuestos de imposibilidad material de obtener el documento, el órgano competente podrá requerirle a la persona interesada su presentación, con anterioridad a la formulación de la propuesta de resolución.
La documentación complementaria se presentará preferiblemente por vía electrónica.
Las personas interesadas se responsabilizarán de la veracidad de los documentos que presenten.
Excepcionalmente, cuando la relevancia del documento en el procedimiento lo exija o existan dudas derivadas de la calidad de la copia, la Administración podrá requerir de manera motivada la exhibición del documento original para el cotejo de la copia electrónica presentada.
Opcionalmente, las personas interesadas podrán presentar la documentación complementaria presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
Siempre que se realice la presentación de documentos separadamente de la solicitud se deberá indicar el código y el órgano responsable del procedimiento, el número de registro de entrada de la solicitud y el número de expediente si se dispone de el.
La sede electrónica de la Xunta de Galicia tiene a disposición de las personas interesadas una serie de modelos normalizados para facilitar la realización de trámites administrativos después de la presentación de las solicitudes de inicio.
Estos modelos se presentarán por medios electrónicos accediendo a la carpeta del ciudadano de la persona interesada.
Cuando las personas no resulten obligadas a la presentación electrónica también podrán presentarlos presencialmente en cualquiera de los registros y lugares establecidos en la normativa reguladora del procedimiento administrativo común.
El objeto de esta orden es la oferta de plazas para las estancias y el tratamiento termal dentro del programa de Bienestar en balnearios 2017 y proceder a su convocatoria.
A tal efecto se entienden por establecimientos balnearios aquellos que disponen de aguas mineromedicinales declaradas de utilidad pública según el artículo 2 del Decreto 402/1996, de 31 de octubre, por el que se aprueba el Reglamento de aprovechamiento de aguas mineromedicinales, termales y de los establecimientos balnearios de la Comunidad Autónoma de Galicia.
Serán personas beneficiarias del programa de Bienestar en balnearios aquellas que reúnan los siguientes requisitos:
Ser mayor de 60 años o mayor de 55 y, en este caso, reunir la condición de pensionista del sistema de la Seguridad Social, por los conceptos de jubilación, invalidez, viudedad u otras pensiones.
Estar empadronado y residir en algún ayuntamiento de la Comunidad Autónoma de Galicia.
Valerse por sí mismo para las actividades de la vida diaria y estar en condiciones de participar en el programa, excepto en el caso de hijos o hijas que acudan en calidad de acompañantes.
No padecer alteraciones del comportamiento que puedan afectar a la normal convivencia en los establecimientos, ni padecer enfermedad transmisible con riesgo de contagio.
Carecer de contraindicación médica para la recepción de los tratamientos termales.
Alcanzar, de conformidad con el baremo establecido, la puntuación que le permita acceder a uno de los balnearios y turnos solicitados.
La persona solicitante podrá ir acompañada de:
Su cónyuge o, en su caso, la pareja de hecho o persona con la que tenga una unión estable y de convivencia con análoga relación a la conyugal, siempre que cumpla los requisitos citados anteriormente, excepto lo señalado en el apartado a) del punto primero.
Un hijo o hija que tenga un grado de discapacidad igual o superior al 33 %, siempre y cuando éste lo pueda hacer sin necesidad de apoyo de tercera persona, se pueda desplazar con autonomía, comparta la habitación con las personas progenitoras y cumpla los requisitos citados en el número 1 de este artículo, excepto el del apartado Una persona con la que dese participar en el programa, siempre y cuando esta cumpla todos los requisitos citados en el número 1 de este artículo.
Las personas solicitantes tendrán que cumplir los requisitos establecidos en la fecha en la que remate el plazo de presentación de solicitudes.
Orden de 8 de marzo de 2017 por la que se regula la oferta de plazas para las estancias y el tratamiento termal dentro del programa de Bienestar en balnearios 2017, y se procede a su convocatoria (DOG nº 53 del 16 de marzo de 2017).
Las solicitudes vendrán acompañadas de la siguiente documentación:
Anexo IV debidamente cubierto, en el caso de que la persona solicitante desee actuar por medio de representante.
Proyecto de intervención detallado según el modelo del anexo VIII, que contenga los siguientes datos mínimos:
Entidad prestadora del servicio. 
Para poder optar a la subvención al amparo de esta orden, la entidad/profesional autónomo prestador del servicio de promoción de la autonomía personal deberá figurar en el Registro de Entidades Prestadoras de Servicios Sociales (RUEPSS), según se disponga en la normativa reguladora de la autorización y acreditación de estos servicios, cuyo responsable es la Consellería de Política Social. 
A estos efectos será suficiente con que la inscripción en el RUEPSS se lleve a cabo con anterioridad al plazo señalado en el artículo 17.2 de esta orden.
Presupuesto detallado del gasto que se va a realizar, según el coste unitario establecido en el artículo 5 de esta orden.
Período de duración de las intervenciones y calendario programado.
Servicios y prestaciones que se ajustarán a las necesidades de atención de la persona solicitante.
Entidad/profesional prestador del servicio.
Declaración del conjunto de todas las ayudas solicitadas o concedidas para la misma actuación o gasto procedentes de cualquier Administración pública o ente público o privado, en el espacio destinado a esta finalidad que figura en el propio modelo de solicitud (anexo III).
Autorización, según el anexo IX, del cónyuge de la persona solicitante o pareja de hecho, en el caso de régimen matrimonial de gananciales, así como de las personas a cargo de la persona solicitante, para la consulta por la Dirección General de Mayores y Personas con Discapacidad de sus datos sobre identidad, residencia, renta (IRPF) y de toda clase de pensiones y prestaciones sociales percibidas. 
Caso contrario, deberán aportar la documentación relacionada con esta información, que, en este caso, sería copia del DNI, certificado de residencia, copia de la declaración del IRPF, certificado de pensiones emitido por el Instituto Nacional de la Seguridad Social, declaración de toda clase de pensiones y prestaciones sociales percibidas.
En su caso, la justificación de la necesidad del transporte adaptado o asistido para el disfrute de otro servicio/prestación social, o como medio de asistencia al trabajo o a una actividad formativa no obligatoria del Sistema público educativo cuando no se enmarque dentro del ámbito de las competencias propias del Sistema educativo, de conformidad con lo previsto en el artículo 4.1, según el tipo de actuación para la que se solicita la ayuda.
La información relativa a los indicadores comunes de ejecución sobre participantes a los que se refiere el anexo I del Reglamento (UE) Nº 1304/2013, del Parlamento Europeo y del Consejo, de 17 de septiembre de 2013, relativo al Fondo Social Europeo, según el modelo del anexo VI.
Las solicitudes deberán presentarse preferiblemente por vía electrónica a través del formulario normalizado disponible en la sede electrónica de la Xunta de Galicia, https://sede.xunta.gal. 
Para la presentación de las solicitudes se podrá emplear cualquiera de los mecanismos de identificación y firma admitidos por la sede electrónica de la Xunta de Galicia, incluido el sistema de usuario y clave Chave365, que puede solicitar accediendo a la web https://sede.xunta.gal/chave365.
Opcionalmente, también se podrán presentar las solicitudes en soporte papel en cualquiera de los lugares y registros establecidos en los artículos 14.1 y 16.4 de la Ley 39/2015, de 1 de octubre, utilizando el formulario normalizado disponible en la sede electrónica de la Xunta de Galicia.
La solicitud, según el modelo que se aporta como anexo III a esta orden, se dirigirá al órgano de dirección con competencias en materia de dependencia de la Consellería de Política Social-Dirección General de Mayores y Personas con Discapacidad.
La documentación complementaria se presentará preferiblemente por vía electrónica. 
Las personas interesadas se responsabilizarán de la veracidad de los documentos que presenten. 
La Administración podrá requerir la exhibición del documento original para el cotejo de la copia electrónica presentada.
Opcionalmente, las personas interesadas podrán presentar la documentación complementaria presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
Siempre que se realice la presentación de documentos separadamente de la solicitud se deberá indicar el código y el órgano responsable del procedimiento, el número de registro de entrada de la solicitud y el número de expediente si dispone de él.
La sede electrónica de la Xunta de Galicia tiene a disposición de las personas interesadas una serie de modelos normalizados para facilitar la realización de trámites administrativos después de la presentación de las solicitudes de inicio. 
Estos modelos se presentarán preferentemente por medios electrónicos accediendo a la carpeta del ciudadano de la persona interesada. 
Cuando las personas interesadas no resulten obligadas a la presentación electrónica de las solicitudes también podrán presentarlos presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
En el plazo de presentación de solicitudes, se entenderá que el plazo vence el día cuyo ordinal coincida con el que sirvió de partida, que es el de la publicación en el Diario Oficial de Galicia, y, si es festivo, el primer día hábil siguiente.
Esta orden tiene por objeto establecer las bases reguladoras de la convocatoria pública para la concesión de ayudas individuales destinadas a la adquisición de servicios de promoción de la autonomía personal, así como la adquisición de servicios complementarios de asistencia personal, para personas con discapacidad empadronadas en un municipio de la Comunidad Autónoma de Galicia, en régimen de concurrencia competitiva y de carácter no periódico.
La finalidad de estas ayudas es la de colaborar en determinados gastos, con efectos de 1 de enero de 2017, destinados a:
Facilitar la adquisición de servicios de promoción de la autonomía personal.
Facilitar a adquisición de servicios complementarios de asistencia personal.
Únicamente podrán ser objeto de financiación para esta convocatoria las actuaciones que se realicen entre el 1 de enero y el 30 de noviembre de 2017.
Adquisición de servicios de promoción de la autonomía personal que tienen por finalidad desarrollar y mantener la capacidad personal de controlar, afrontar y tomar decisiones acerca de como vivir de acuerdo con las normas y preferencias propias y facilitar la ejecución de las actividades básicas de la vida diaria, de manera que todas las personas puedan llevar una vida lo más autónoma posible. 
Se consideran servicios de promoción de la autonomía personal subvencionables al amparo de esta orden los enumerados en el anexo I, de acuerdo con lo dispuesto en el Decreto 149/2013, de 5 de septiembre, por el que se define la cartera de servicios sociales para la promoción de la autonomía personal y la atención a las personas en situación de dependencia y se determina el sistema de participación de las personas usuarias en la financiación de su coste.
Para poder ser subvencionable el servicio de transporte adaptado o asistido, deberá de justificarse la vinculación de este servicio para el disfrute del otro servicio/prestación social, o como medio de asistencia al trabajo o a una actividad formativa no obligatoria del Sistema público educativo cuando no se enmarque dentro del ámbito de las competencias propias del Sistema educativo.
Adquisición de servicios complementarios de asistencia personal que, de conformidad con el Decreto 149/2013, de 5 de septiembre, serán subvencionables:
Asistencia en las necesidades de carácter doméstico y de la vivienda.
Asistencia en las actividades básicas de la vida diaria.
Asistencia en gestiones administrativas o de otra naturaleza fuera del domicilio.
Asistencia en actividades de participación social, educativa, laboral o de ocio.
Podrán ser personas beneficiarias de las ayudas reguladas en esta orden:
Personas que tengan reconocido un grado de discapacidad igual o superior al 33 por ciento, según lo establecido en el Real decreto 1971/1999, de 23 de diciembre, de procedimiento para el reconocimiento, declaración y calificación del grado de discapacidad, y la Orden de 25 de noviembre de 2015 por la que se regula el procedimiento para el reconocimiento, declaración y calificación del grado de discapacidad en Galicia. 
Asimismo, se considerará que presentan una discapacidad en grado igual o superior al 33 por ciento los pensionistas de la Seguridad Social que tengan reconocida una pensión de incapacidad permanente en el grado de total, absoluta o gran invalidez, y los pensionistas de clases pasivas que tengan reconocida una pensión de jubilación o de jubilación por incapacidad permanente para el servicio o inutilidad.
También podrán optar a solicitar las ayudas reguladas en esta convocatoria las personas que hayan solicitado el reconocimiento del grado de discapacidad con anterioridad a la fecha de publicación de esta convocatoria, quedando condicionada la percepción de la ayuda a que les sea reconocido un grado de discapacidad igual o superior al 33 por ciento, dentro del plazo máximo establecido para la resolución de esta convocatoria de ayudas, según lo señalado en el artículo 14.2. 
En este caso, la tramitación del expediente de reconocimiento del grado de discapacidad tendrá carácter prioritario.
En cuanto a las personas solicitantes de servicios complementarios de asistencia personal será necesario, además de cumplir con el requisito dispuesto en el apartado anterior, que la persona solicitante tenga reconocida la prestación de asistencia personal a través del Sistema para la autonomía y atención a la dependencia, según lo establecido en el Decreto 15/2010, de 4 de febrero, por el que se regula el procedimiento para el reconocimiento de la situación de dependencia y del derecho a las prestaciones del Sistema para la autonomía y atención a la dependencia, el procedimiento para la elaboración del Programa individual de atención y la organización y funcionamiento de los órganos técnicos competentes.
A los efectos de reconocer la necesidad de la ayuda individual solicitada en relación a la adquisición del servicio de promoción al que se vincula, será requisito necesario que sea determinada la situación de necesidad acorde a la situación de salud y social de la persona solicitante. 
La situación de necesidad se valorará de acuerdo con las dificultades o carencias importantes en la atención de las necesidades de la persona solicitante o en su integración social, entendiendo el concepto de necesidad en un sentido amplio: de subsistencia, de salud, de carácter social, de desarrollo personal, de autonomía, etc., con un cierto grado de intensidad.
A estos efectos, será emitido un informe de oficio por la Unidad de Coordinación de la Dependencia de la Subdirección General de la Dependencia y Valoración de la Discapacidad, donde se valore este extremo en base a la documentación obrante en el expediente de reconocimiento del grado de discapacidad de la persona solicitante, y que, en su caso, podrá solicitar aquellos informes complementarios o documentos que se consideren necesarios a tal fin.
En caso de que por el elevado número de solicitudes se haga necesario, el informe de oficio podrá ser emitido por los equipos técnicos de los servicios de dependencia y autonomía personal territoriales, previa instrucción sobre los extremos a valorar, emitida por la persona titular del órgano de dirección con competencias en materia de dependencia y discapacidad de la Consellería de Política Social.
Las personas beneficiarias de la ayuda vienen obligadas a destinar el importe de esta a la finalidad para la que les fue concedida.
Además, las personas beneficiarias de las ayudas están obligadas, conforme a lo dispuesto en el artículo 11 de la Ley 9/2007, de 13 de junio, a:
Conservar los documentos justificativos de la aplicación de los fondos recibidos, en tanto puedan ser objeto de actuaciones de comprobación y control.
Facilitar toda la información requerida por la Dirección General de Mayores y Personas con Discapacidad, por los órganos verificadores que se establezcan en aplicación de los artículos 72, 73 y 74 del Reglamento (UE) nº 1303/2013 del Parlamento Europeo y del Consejo, de 17 de diciembre de 2013, que contemplarán las correspondientes visitas sobre el terreno, así como por la Intervención General de la Comunidad Autónoma, el Tribunal de Cuentas, el Consejo de Cuentas, y otros órganos de control impuestos por la normativa comunitaria en el ejercicio de sus funciones de fiscalización y control.
Someterse a las actuaciones de comprobación, que efectuará el órgano concedente, así como a través de la Subdirección General de Autorización e Inspección de Servicios Sociales de la Secretaría General Técnica de la consellería con competencias en materia de servicios sociales.
Proceder al reintegro de los fondos percibidos en los supuestos previstos en el artículo 33 de la citada ley y según lo dispuesto en el artículo 16 y 19.
Comunicar cualquier variación que se produzca en relación al proyecto de intervención o en su calendario.
Facilitar la información suficiente relativa al desarrollo de las actuaciones que permita dar cumplimiento a los requisitos de información a través de indicadores de ejecución e indicadores de resultado inmediato previstos en el artículo 5 del Reglamento (UE) nº 1304/2013 del Parlamento Europeo y del Consejo, de 17 de diciembre de 2013, relativo al FSE. 
En este sentido, esta información se aportará empleando el modelo que figura en el anexo V, y en la cobertura de los mismos deberá respetarse el principio de integridad de los datos.
Los indicadores de ejecución relativos a la persona solicitante se refieren a la fecha inmediatamente anterior al inicio de la vinculación del participante con las actuaciones subvencionadas, mientras que los indicadores de resultado inmediato deberán referirse al período comprendido entre el día posterior a la finalización de su vinculación con la operación y las cuatro semanas siguientes, en el período de justificación de la correspondiente subvención.
Asimismo, la Administración podrá requerir nuevos datos en el plazo de seis meses desde que finalice la vinculación del participante con la actividad cofinanciada, con la finalidad de formalizar los indicadores de resultado a largo plazo descritos en el antedicho reglamento.
Según lo dispuesto en el artículo 4, apartados 1 y 2, de la Ley 1/2016, de 18 de enero, de transparencia y buen gobierno, las personas beneficiarias están obligadas a suministrar a la consellería, previo requerimiento, toda la información necesaria para el cumplimiento por aquella de las obligaciones previstas en la referida ley.
Residir en la Comunidad Autónoma de Galicia.
Que la necesidad de la ayuda solicitada derive de una tipología de discapacidad reconocida.
Que las consecuencias derivadas de la tipología de discapacidad reconocida, que sirvan de base para valorar la necesidad de la subvención concedida, mantengan su vigencia en el período de referencia concretado en el proyecto de intervención objeto de subvención.
Que la capacidad económica de la persona solicitante, calculada conforme a lo previsto en el artículo 13, no supere el 200 % del indicador público de la renta de efectos múltiples mensual (IPREM) establecido para el año 2017.
No percibir durante el año 2017 otras ayudas para el mismo fin salvo que la ayuda individual solicitada sea complementaria de la anteriormente concedida y en este caso hasta el límite del 100  % del gasto subvencionado, a efectos de prever la situación de dependencia o de promover la autonomía personal de la persona solicitante.
Los establecidos con carácter general para obtener la condición de persona beneficiaria de subvenciones en el artículo 10 de la Ley 9/2007, de 13 de junio, de subvenciones de Galicia.
El resto de las solicitudes, que reuniendo los requisitos y por puntuación no obtengan plaza, quedarán en reserva para ser atendidas en el supuesto de quedar plazas vacantes por producirse alguna renuncia.
Evaluadas las solicitudes, siguiendo los criterios establecidos en el anexo V de esta orden, la comisión de valoración emitirá un informe en base al cual el Servicio de Prevención de la Dependencia, en sus competencias como órgano instructor, elevará al órgano competente una propuesta de resolución.
En esta propuesta figurarán las solicitudes propuestas para la concesión de plaza, hasta agotar el número de plazas ofertadas.
El plazo máximo para resolver y notificar las resoluciones es de tres meses, a contar desde el día siguiente al de la publicación de esta orden en el Diario Oficial de Galicia.
Transcurrido dicho plazo sin que desde la Dirección General de Mayores y Personas con Discapacidad se notificara resolución expresa, las personas solicitantes podrán entender desestimadas sus peticiones por silencio administrativo, de conformidad con lo establecido en el artículo 25.1 de la Ley 39/2015, de 1 de octubre, del procedimiento administrativo común de las administraciones públicas.
Las notificaciones de resoluciones y actos administrativos se practicarán preferentemente por medios electrónicos y, en todo caso, cuando las personas interesadas resulten obligadas a recibirlas por esta vía.
Si el envío de la notificación electrónica no fuera posible por problemas técnicos, la Administración general y las entidades del sector público autonómico practicarán la notificación por los medios previstos en la normativa reguladora del procedimiento administrativo común.
Una vez notificada la concesión de la plaza, para poder hacer uso de ella, las personas beneficiarias tienen la obligación de confirmar por escrito, y en el plazo que se les indique en la resolución de concesión, su aceptación acompañada del justificante de haber remitido a la dirección del balneario, por giro postal u otros medios, la cantidad de 30 euros en concepto de reserva de plaza.
En el supuesto de que no se cumplan las condiciones establecidas en el párrafo anterior, no se formalizará la adjudicación definitiva de la plaza y se entenderá que se renuncia a ella, pudiendo otorgarle esa plaza vacante a otra persona de la lista de espera.
Si la persona beneficiaria abandona la estancia una vez iniciada, cualquiera que fuera el motivo, no tendrá derecho a ningún tipo de devolución.
Los establecimientos termales en los que se lleva a cabo el programa quedarán sujetos a la supervisión y seguimiento directo y al control de la calidad de los servicios prestados, por parte de la Consellería de Política Social.
La consignación o aportación de datos o documentos falseados o inexactos para la obtención de las plazas reguladas por la presente orden, implicará la cancelación de la plaza obtenida, en el supuesto de que no se participase en el turno, o la obligación, por parte de la persona interesada, de abonar el precio real de la plaza, sin perjuicio de las acciones que procedan en aplicación de la normativa vigente, si ya disfrutara del turno.


La Ley 13/2008, de 3 de diciembre, de servicios sociales de Galicia, establece, en su artículo 1, que los poderes públicos gallegos deberán posibilitar que la libertad y la igualdad de las personas sean reales y efectivas, facilitando la participación de todas y todos en la vida política, económica, social y cultural.
Entre las competencias que le corresponden a la Consellería de Política Social según el Decreto 176/2015, de 3 de diciembre, por el que se establece la estructura orgánica de este departamento, están las relativas a las políticas en materia de bienestar destinadas a la atención de las personas mayores, teniendo entre las funciones encomendadas el desarrollo de programas y actividades de promoción de la autonomía personal, así como la promoción del envejecimiento activo.
En el marco de esas competencias, y siendo conscientes de que en la promoción de la autonomía personal están las claves para que las personas mayores puedan disfrutar de una vida más saludable e independiente, y teniendo como precedente la Estrategia para la prevención y detección precoz de la dependencia, se elaboró el nuevo documento marco de planificación: la Estrategia gallega de envejecimiento activo desde la Innovación 2016-2020.7
Marco de actuación para una vida activa, saludable, independiente y segura, que en su primera línea estratégica, llamada aprendiendo a envejecer, considera a la persona como responsable de su propio proceso de envejecimiento saludable y para ello contempla actuaciones destinadas al fomento de actitudes positivas de cara al cuidado de la salud y a la promoción de la autonomía personal, la promoción de hábitos de vida saludables desde la etapa adulta a través de la gestión del autocuidado y el impulso de las terapias no farmacológicas para promover la autonomía personal y favorecer las relaciones sociales.
En este sentido es necesario también señalar que el aumento de la esperanza y de la calidad de vida, otorga a las personas mayores un peso cada vez más importante en la sociedad y estas personas demandan su participación plena y activa en los distintos ámbitos de nuestra sociedad y manifiestan su deseo de pasar un período de vacaciones en un establecimiento termal, donde el tratamiento propiamente dicho, junto al descanso y la relación social, les proporcionan una mejoría en su salud y bienestar y, en definitiva, una mejor calidad de vida.
Por ello, y dando cumplimiento a lo establecido en la primera línea de dicha estrategia, se desarrolla el programa de termalismo Bienestar en balnearios, en tanto que los balnearios son espacios propicios para obtener una mayor calidad de vida, y por lo tanto los tratamientos que en los mismos se prestan contribuyen a hacer realidad la concepción que de la salud tiene la Organización Mundial de la Salud: un estado de completo bienestar físico, mental y social. 
Los tratamientos de prevención y rehabilitación que se realizan mediante el uso terapéutico de las aguas mineromedicinales, son una práctica muy antigua, a la que se fueron incorporando técnicas complementarias de diferentes ámbitos buscando una mayor eficacia en los tratamientos. 
El colectivo de las personas mayores es uno de los que más beneficios puede obtener de tales prácticas, dado que, a medida que avanza la edad, tienden a aparecer determinadas patologías que pueden mejorar notablemente después de recibir un tratamiento termal.
Conforme a lo expuesto, y haciendo uso de las facultades que me confiere el artículo 34 de la Ley 1/1983, de 22 de febrero, de normas reguladoras de la Xunta y de su Presidencia, el conselleiro de Política Social, conforme a las facultades que tengo atribuidas,
El objeto de esta orden es la oferta de plazas para las estancias y el tratamiento termal dentro del programa de Bienestar en balnearios 2017 y proceder a su convocatoria.
A tal efecto se entienden por establecimientos balnearios aquellos que disponen de aguas mineromedicinales declaradas de utilidad pública según el artículo 2 del Decreto 402/1996, de 31 de octubre, por el que se aprueba el Reglamento de aprovechamiento de aguas mineromedicinales, termales y de los establecimientos balnearios de la Comunidad Autónoma de Galicia.
Serán personas beneficiarias del programa de Bienestar en balnearios aquellas que reúnan los siguientes requisitos:
Ser mayor de 60 años o mayor de 55 y, en este caso, reunir la condición de pensionista del sistema de la Seguridad Social, por los conceptos de jubilación, invalidez, viudedad u otras pensiones.
 Estar empadronado y residir en algún ayuntamiento de la Comunidad Autónoma de Galicia.
Valerse por sí mismo para las actividades de la vida diaria y estar en condiciones de participar en el programa, excepto en el caso de hijos o hijas que acudan en calidad de acompañantes.
No padecer alteraciones del comportamiento que puedan afectar a la normal convivencia en los establecimientos, ni padecer enfermedad transmisible con riesgo de contagio.
Carecer de contraindicación médica para la recepción de los tratamientos termales.
Alcanzar, de conformidad con el baremo establecido, la puntuación que le permita acceder a uno de los balnearios y turnos solicitados.
Su cónyuge o, en su caso, la pareja de hecho o persona con la que tenga una unión estable y de convivencia con análoga relación a la conyugal, siempre que cumpla los requisitos citados anteriormente, excepto lo señalado en el apartado a) del punto primero.
 Un hijo o hija que tenga un grado de discapacidad igual o superior al 33 %, siempre y cuando éste lo pueda hacer sin necesidad de apoyo de tercera persona, se pueda desplazar con autonomía, comparta la habitación con las personas progenitoras y cumpla los requisitos citados en el número 1 de este artículo, excepto el del apartado a).
Una persona con la que desee participar en el programa, siempre y cuando esta cumpla todos los requisitos citados en el número 1 de este artículo.
Las personas solicitantes tendrán que cumplir los requisitos establecidos en la fecha en la que remate el plazo de presentación de solicitudes.
Se convocan 600 plazas para participar en el programa de Bienestar en balnearios de la Xunta de Galicia 2017, que se llevarán a cabo en los turnos y establecimientos termales que se relacionan en el anexo IV de la presente orden.
Los turnos tienen una duración de 10 días, con nueve noches cada una, y comprenderán desde las doce horas del día de llegada hasta las doce horas del día de salida.
 El desarrollo de estos turnos tendrá lugar durante el período comprendido entre el mes de abril y el de diciembre de 2017.
Alojamiento y manutención en régimen de pensión completa y en habitaciones dobles, de uso compartido.
Tratamientos termales, con las indicaciones terapéuticas que figuran para cada balneario en el anexo IV que comprenderán:
El reconocimiento médico, al ingresar en el balneario, para la prescripción del tratamiento.
El tratamiento termal básico que, en cada caso, prescriba el personal médico del balneario.
Programa de actividades de animación sociocultural que se lleve a cabo en el establecimiento hotelero o termal.
Las personas beneficiarias que estén interesadas en alojarse en habitación individual, en el caso de que hubiera disponibilidad, se tendrán que hacer cargo de la diferencia del coste que suponga, y las que precisen de algún tipo de apoyo o dieta especial lo tendrán que indicar en el momento de presentar la solicitud e acreditarlo al incorporarse al turno.
 Las personas beneficiarias que estén interesadas en participar en las excursiones o actividades con coste adicional que organice el establecimiento termal o hotelero, lo deberán de hacer por sus propios medios y a su cargo.
El desplazamiento desde el domicilio hasta el establecimiento termal así como el de regreso correrá a cargo de las personas beneficiarias, sin perjuicio de que se puedan acoger a las facilidades para el transporte que oferte el balneario, en su caso.
El precio a pagar por las personas beneficiarias, por plaza y turno para cada balneario, es el que figura en el anexo IV.
Dicho importe es un precio cerrado para todos los servicios incluidos en el turno, sin que proceda efectuar deducción alguna si por cualquier causa imputable a la persona beneficiaria ésta no disfrute de la totalidad de dichos servicios.
La Consellería de Política Social contribuirá a la financiación del precio de la estancia con una aportación de un 27 % del coste de la plaza en cada establecimiento termal y el resto del importe hasta completar el coste de la plaza correrá a cargo de la persona beneficiaria.
Las solicitudes se presentarán preferiblemente por vía electrónica a través del formulario normalizado disponible en la sede electrónica de la Xunta de Galicia, https://sede.xunta.gal.
Opcionalmente, se podrán presentar las solicitudes presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
Para la presentación de las solicitudes se podrá emplear cualquiera de los mecanismos de identificación y firma admitidos por la sede electrónica de la Xunta de Galicia, incluido el sistema de usuario y clave Chave365 (https://sede.xunta.gal/chave365).
Las solicitudes se formularán en el modelo oficial que se indica en el anexo I de esta orden.
En cada solicitud sólo se podrá relacionar un máximo de tres destinos por orden de prioridad.
No será necesario aportar los documentos que ya fueran presentados anteriormente.
A estos efectos, la persona interesada deberá indicar en qué momento y ante qué órgano administrativo presentó los citados documentos. 
Se presumirá que esta consulta es autorizada por las personas interesadas, salvo que conste en el procedimiento su oposición expresa.
En los supuestos de imposibilidad material de obtener el documento, el órgano competente podrá requerirle a la persona interesada su presentación, con anterioridad a la formulación de la propuesta de resolución.
La documentación complementaria se presentará preferiblemente por vía electrónica. 
Las personas interesadas se responsabilizarán de la veracidad de los documentos que presenten. 
Excepcionalmente, cuando la relevancia del documento en el procedimiento lo exija o existan dudas derivadas de la calidad de la copia, la Administración podrá requerir de manera motivada la exhibición del documento original para el cotejo de la copia electrónica presentada.
Opcionalmente, las personas interesadas podrán presentar la documentación complementaria presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
Siempre que se realice la presentación de documentos separadamente de la solicitud se deberá indicar el código y el órgano responsable del procedimiento, el número de registro de entrada de la solicitud y el número de expediente si se dispone de el.
Para la tramitación de este procedimiento se consultarán automáticamente los datos incluidos en los siguientes documentos elaborados por las administraciones públicas:
En el caso de que las personas interesadas o acompañantes se opongan a esta consulta deberán indicarlo en el cuadro habilitado en el modelo de solicitud o en los anexos II o III, según de lo que se trate, y aportar los documentos correspondientes.
Excepcionalmente, en el caso de que alguna circunstancia imposibilitase la obtención de los citados datos se podrá solicitar a las personas interesadas la presentación de los documentos correspondientes.
La sede electrónica de la Xunta de Galicia tiene a disposición de las personas interesadas una serie de modelos normalizados para facilitar la realización de trámites administrativos después de la presentación de las solicitudes de inicio. 
Estos modelos se presentarán por medios electrónicos accediendo a la carpeta del ciudadano de la persona interesada. 
Cuando las personas no resulten obligadas a la presentación electrónica también podrán presentarlos presencialmente en cualquiera de los registros y lugares establecidos en la normativa reguladora del procedimiento administrativo común.
El plazo para la presentación de las solicitudes será de veinte (20) días hábiles contados a partir del día siguiente al de la publicación de esta orden en el Diario Oficial de Galicia.
Los servicios de Dependencia y Autonomía Personal de las jefaturas territoriales de la Consellería de Política Social realizarán de oficio cuantas actuaciones estimen necesarias para la determinación, el conocimiento y la comprobación de los datos que constan en la solicitud y se exigen en esta orden.
Asimismo, de conformidad con lo establecido en el artículo 68 de la Ley 39/2015, de 1 de octubre, del procedimiento administrativo común de las administraciones públicas, si la solicitud no reúne alguno de los requisitos exigidos en la presente orden, requerirán a las personas interesadas para que, en un plazo de diez (10) días hábiles, subsanen la falta o aporten los documentos preceptivos. 
En este requerimiento se hará indicación expresa de que, si así no lo hiciesen, se tendrán por desistidas de su petición, después de la correspondiente resolución.
En los expedientes que estén completos, será el Servicio de Prevención de la Dependencia de la Dirección General de Mayores y Personas con Discapacidad el que continúe con la instrucción y procederá a su remisión a la comisión encargada de la valoración.
Se constituirá en la Dirección General de Mayores y Personas con Discapacidad una comisión de valoración a estos efectos que, de acuerdo con los criterios de baremación establecidos en el anexo V de la presente orden, realizará la selección y emitirá el correspondiente informe en el que se concrete el resultado de la baremación efectuada.
La comisión de valoración estará integrada por la persona titular de la Subdirección General de Promoción de la Autonomía Personal y Prevención de la Dependencia o persona que la sustituya, que actuará como presidente/a, por la persona titular del Servicio de Prevención de la Dependencia, y por dos personas de dicho servicio, actuando una de éstas como secretario/a y procurando alcanzar el principio de presencia equilibrada entre hombres y mujeres. 
La comisión podrá adoptar válidamente sus acuerdos siempre que asistan la persona que ejerce la presidencia, la que actúa como secretario/a y la mitad de sus miembros. 
Si, por cualquier causa, alguna de las personas que componen la comisión de valoración no pudiera asistir cuando ésta se reúna, será sustituida por la persona funcionaria designada a estos efectos por quien ejerza la presidencia.
Evaluadas las solicitudes, siguiendo los criterios establecidos en el anexo V de esta orden, la comisión de valoración emitirá un informe en base al cual el Servicio de Prevención de la Dependencia, en sus competencias como órgano instructor, elevará al órgano competente una propuesta de resolución. 
En esta propuesta figurarán las solicitudes propuestas para la concesión de plaza, hasta agotar el número de plazas ofertadas. 
El resto de las solicitudes, que reuniendo los requisitos y por puntuación no obtengan plaza, quedarán en reserva para ser atendidas en el supuesto de quedar plazas vacantes por producirse alguna renuncia.
La resolución le corresponde a la persona titular de la Dirección General de Mayores y Personas con Discapacidad, por delegación de la persona titular de la Consellería de Política Social.
El plazo máximo para resolver y notificar las resoluciones es de tres meses, a contar desde el día siguiente al de la publicación de esta orden en el Diario Oficial de Galicia. Transcurrido dicho plazo sin que desde la Dirección General de Mayores y Personas con Discapacidad se notificara resolución expresa, las personas solicitantes podrán entender desestimadas sus peticiones por silencio administrativo, de conformidad con lo establecido en el artículo 25.1 de la Ley 39/2015, de 1 de octubre, del procedimiento administrativo común de las administraciones públicas.
Las notificaciones de resoluciones y actos administrativos se practicarán preferentemente por medios electrónicos y, en todo caso, cuando las personas interesadas resulten obligadas a recibirlas por esta vía. 
Las personas interesadas que no estén obligadas a recibir notificaciones electrónicas podrán decidir y comunicar en cualquier momento que las notificaciones sucesivas se practiquen o dejen de practicar por medios electrónicos.
Las notificaciones electrónicas se realizarán mediante el Sistema de notificación electrónica de Galicia Notifica.gal disponible a través de la sede electrónica de la Xunta de Galicia (https://sede.xunta.gal). 
Este sistema remitirá a las personas interesadas avisos de la puesta a disposición de las notificaciones al dispositivo electrónico y/o a la dirección de correo electrónico que consten en la solicitud. 
Estos avisos no tendrán, en ningún caso, efectos de notificación practicada y su carencia no impedirá que la notificación sea considerada plenamente válida.
La persona interesada deberá manifestar expresamente la modalidad escogida para la notificación (electrónica o en papel). 
En el caso de personas interesadas obligadas a recibir notificaciones sólo por medios electrónicos deberán optar en todo caso por la notificación por medios electrónicos, sin que sea válida, ni produzca efectos en el procedimiento, una opción diferente.
Las notificaciones por medios electrónicos se entenderán practicadas en el momento en el que se produzca el acceso a su contenido. 
Cuando la notificación por medios electrónicos sea de carácter obligatorio, o fuera expresamente elegida por la persona interesada, se entenderá rechazada cuando transcurriesen diez días naturales desde la puesta a disposición de la notificación sin que se acceda a su contenido.
Si el envío de la notificación electrónica no fuera posible por problemas técnicos, la Administración general y las entidades del sector público autonómico practicarán la notificación por los medios previstos en la normativa reguladora del procedimiento administrativo común.
En las resoluciones de concesión se indicará el balneario y el turno en que el que se le otorga la plaza, el coste y el importe a pagar en concepto de reserva de plaza, los trámites necesarios para formalizar la adjudicación definitiva, así como la documentación y material o accesorios que necesita levar para incorporarse al programa.
Las resoluciones dictadas ponen fin a la vía administrativa y, contra ellas, podrá interponerse potestativamente recurso de reposición ante el órgano que dictó el acto, en el plazo de un mes desde su notificación, de acuerdo con lo dispuesto en los artículos 123 y 124 de la Ley 39/2015, de 1 de octubre, del procedimiento administrativo común de las administraciones públicas o, directamente, recurso contencioso-administrativo ante el órgano jurisdiccional competente, en el plazo de dos meses contados desde el día siguiente al de su notificación, de conformidad con lo establecido en la Ley 29/1998, de 13 de julio, reguladora de la jurisdicción contencioso-administrativa.
Una vez notificada la concesión de la plaza, para poder hacer uso de ella, las personas beneficiarias tienen la obligación de confirmar por escrito, y en el plazo que se les indique en la resolución de concesión, su aceptación acompañada del justificante de haber remitido a la dirección del balneario, por giro postal u otros medios, la cantidad de 30 euros en concepto de reserva de plaza.
En el supuesto de que no se cumplan las condiciones establecidas en el párrafo anterior, no se formalizará la adjudicación definitiva de la plaza y se entenderá que se renuncia a ella, pudiendo otorgarle esa plaza vacante a otra persona de la lista de espera.
Ninguna persona solicitante que se haya beneficiado de algún turno de este programa podrá participar en ningún otro, ni en calidad de acompañante, excepto que se trate de una plaza para la que no haya ninguna otra persona adjudicataria.
Las personas solicitantes que, cumpliendo los requisitos establecidos en el artículo 2 de esta orden, no obtengan plaza, quedarán incluidas en una lista de espera, que estará publicada en la página web de la Consellería de Política Social: http://www.xunta.gal/politica-social, y serán llamadas por rigorosa orden de puntuación, según se vayan produciendo vacantes.
Las personas que formalicen su adjudicación definitiva abonarán directamente en el balneario, cuando se incorporen al turno, el importe resultante de la diferencia entre la cantidad fijada como precio para la plaza y la cantidad ya aportada en concepto de gastos de gestión de la reserva de plaza.
Por su parte, la Consellería de Política Social, irá efectuando el pago del importe establecido para cada uno de los establecimientos termales una vez que éstos presenten las correspondientes facturas de haber prestado el servicio en los términos acordados.
El importe abonado en concepto de reserva de plaza no se le devolverá a la persona adjudicataria de la plaza en ningún caso.
Si la persona beneficiaria abandona la estancia una vez iniciada, cualquiera que fuera el motivo, no tendrá derecho a ningún tipo de devolución.
Los establecimientos termales en los que se lleva a cabo el programa quedarán sujetos a la supervisión y seguimiento directo y al control de la calidad de los servicios prestados, por parte de la Consellería de Política Social.
Además de las circunstancias establecidas en el artículo 14 de esta orden, si no se confirma la adjudicación de la plaza concedida, también perderán la condición de persona beneficiaria del programa aquellas que no abonen al establecimiento termal, al comienzo del turno, el resto de la cantidad estipulada para la plaza que se le otorgó.
La consignación o aportación de datos o documentos falseados o inexactos para la obtención de las plazas reguladas por la presente orden, implicará la cancelación de la plaza obtenida, en el supuesto de que no se participase en el turno, o la obligación, por parte de la persona interesada, de abonar el precio real de la plaza, sin perjuicio de las acciones que procedan en aplicación de la normativa vigente, si ya disfrutara del turno.
La presentación de la solicitud implica la aceptación de las normas de este procedimiento.
Esta disposición tiene por objeto establecer las bases que rigen los premios Artesanía de Galicia, que se aprueban en el anexo I y proceder a su convocatoria para el año 2017 con el objetivo de reconocer la mejora continua en la labor de los profesionales del sector artesano gallego y contribuir a su desarrollo económico y promocional.
Estas bases tienen por objeto regular la concesión de los premios de Artesanía de Galicia como un reconocimiento a la mejora continua en la labor de los profesionales del sector artesano gallego y contribuir a su desarrollo económico y promocional.
Se premiará la obra que represente las líneas deseadas para una artesanía competitiva en el mercado actual como son el diseño, la adaptación o la conservación de las técnicas y valores tradicionales más característicos de nuestra artesanía, la incorporación a las tendencias actuales, la innovación, la buena presentación y la calidad de la obra tanto en sus materiales como en el desarrollo de ésta.
Premio honorífico en reconocimiento a la trayectoria profesional consolidada de una persona artesana gallega. 
El premio será concedido teniendo en cuenta las propuestas de los talleres artesanales inscritos en el Registro General de Artesanía, las asociaciones profesionales de artesanos de Galicia y otras entidades públicas o privadas encargadas de hacer la presentación de las candidaturas. 
Se valorará la trayectoria reconocida de la persona candidata, su contribución, puesta en valor y promoción de la artesanía gallega, la calidad de los trabajos realizados y el compromiso con la divulgación y transmisión pedagógica de los principales valores positivos en el campo de nuestra artesanía.
Esta modalidad tiene la finalidad de potenciar el relevo generacional en la artesanía, el acceso de nuevos talentos al sector y su profesionalización. 
Se premiará la candidatura que presente una propuesta para su formación en un centro formativo o en un taller artesanal de referencia en el campo de la artesanía y el diseño. 
Se valorará el carácter innovador del proyecto, la transferencia de conocimiento que se pretende lograr con esa formación, la incorporación de las nuevas tecnologías, el currículo de la persona candidata y la potencialidad de incorporación de esta formación para la elaboración de un producto artesanal innovador. 
También se tendrá en cuenta el grado de madurez, calidad en la presentación de la propuesta, así como la colaboración entre distintas actividades artesanales.
Talleres artesanales inscritos en el Registro General de Artesanía de Galicia cuyo titular sea una persona artesana registrada como tal, de acuerdo con la Ley 1/1992, de 11 de marzo, de artesanía de Galicia, y con el Decreto 218/2001, de 7 de septiembre, por el que se refunde la normativa vigente en materia de artesanía.
Artesanos/as en activo o retirados que están o estuvieron inscritos como tales en el Registro General de Artesanía de Galicia y con una actividad mínima y demostrable en el sector de 20 años. 
Los encargados de hacer la presentación de las candidaturas de esta categoría serán los talleres artesanos inscritos en el Registro General de Artesanía, las asociaciones profesionales de artesanos de Galicia u otras entidades públicas o privadas.
Talleres artesanales inscritos en el Registro General de Artesanía de Galicia y cuyo titular sea una persona artesana registrada como tal y que hubiera alcanzado una edad máxima de 40 años en el 2017.
La sede electrónica de la Xunta de Galicia es la dirección web desde la cuál usted puede ejercer, en condiciones totalmente seguras, su derecho de acceso a la información y a los servicios electrónicos que el gobierno gallego pone a su disposición en https://sede.xunta.gal .
Su titularidad le corresponde a la Consellería de Presidencia, Administraciones Públicas y Justicia de la Xunta de Galicia, que es también la responsable de elaborar y mantener actualizada la relación de los procedimientos y servicios y el resto de contenidos de esta sede.
La gestión tecnológica de la sede le corresponde a la Agencia para la Modernización Tecnológica de Galicia, responsable de la elaboración de los estándares, normas, especificaciones técnicas y guías de estilo en las que se basan los servicios y páginas integradas en esta sede.
La sede electrónica de la Xunta de Galicia se crea y se regula por el Decreto 198/2010, del 2 de diciembre, por el que se regula el desarrollo de la Administración electrónica en la Xunta de Galicia y en las entidades de ella dependientes.
El ámbito de aplicación de la sede electrónica de la Xunta de Galicia comprende la totalidad de los órganos de la Administración general de Galicia y las entidades instrumentales del sector público autonómico, tal como recoge el artículo 1 de la Orden de 15 de septiembre de 2011 por la que se aprueba la puesta en funcionamiento de la sede electrónica de la Xunta de Galicia.
Los certificados de identificación de sede electrónica se emplean, fundamentalmente, para la identificación de las sedes con el fin de asegurarle a la ciudadanía que el establecimiento de comunicaciones con estas se realiza a través de un canal seguro y sin intrusión de terceros.
Para verificar la validez de los certificados de esta sede electrónica, y por lo tanto garantizar su autenticidad, puede emplear la plataforma Valide, del Ministerio de la Presidencia. 
El certificado electrónico de usuario es un sistema de acreditación que permite verificar la identidad de una persona, en este caso del titular de este, y firmar datos y documentos electrónicos que se envíen, de manera que se pueda comprobar su integridad y origen.
La Resolución del 25 de febrero de 2014 por la que se aprueba la política de firma electrónica y de certificados de la Administración general y del sector público autonómico de Galicia adoptó como política de firma electrónica y de certificados de la Administración general y del sector público autonómico de Galicia la política de firma electrónica y de certificados de la Administración general del Estado (OID 2.16.724.1.3.1.1.2.1.9).
Con carácter general, una política de firma electrónica es un documento legal que contiene una serie de normas relativas a la firma electrónica, organizadas alrededor de los conceptos de generación y validación de firma, en un contexto particular (contractual, jurídico, legal), y define las reglas y deberes de todos los actores involucrados en el proceso. 
El objetivo es determinar la validez de la firma electrónica para una transacción en particular, especificando la información que debe incluir la persona firmante en el proceso de generación de la firma y la información que se debe comprobar en el proceso de su validación.
La Xunta de Galicia, examinada la política de firma electrónica y de certificados de la Administración general del Estado, considera que es coherente con el ordenamiento autonómico y plenamente asumible nos sus aspectos técnicos, por lo que, con su adopción, la Administración general y del sector público autonómico de Galicia pretende dar un paso claro para favorecer la interoperabilidad entre administraciones públicas, lo que redundará de una manera inmediata en la simplificación de trámites para los ciudadanos.
Cuando se firman datos, el firmante indica la aceptación de unas condiciones generales y unas condiciones particulares aplicables a aquella firma electrónica mediante la inclusión de un campo firmado, dentro de la firma, que específica una política explícita o implícita.
Si el campo correspondiente a la normativa de firma electrónica está ausente y no se identifica ninguna normativa como aplicable, entonces se puede asumir que la firma ha sido generada o verificada sin ninguna restricción normativa, y en consecuencia, que no se le ha asignado ningún significado concreto legal o contractual. 
Se trataría de una firma que no especifica de forma expresa ninguna semántica o significación concreta y, por lo tanto, hará falta derivar el significado de la firma a partir del contexto (y especialmente, de la semántica del documento firmado).
La finalidad de una política de firma es reforzar la confianza en las transacciones electrónicas a través de una serie de condiciones para un contexto dado, el cual puede ser una transacción determinada, un requisito jurídico o un rol que asuma la parte firmante, entre otros. 
Este documento especifica las condiciones generales aplicables a la firma electrónica para su validación, en la relación electrónica de la Administración General del Estado (AGE) y sus organismos públicos vinculados o dependientes con los ciudadanos y entre los órganos y entidades de la AGE y sus organismos públicos vinculados o dependientes.
La política de firma electrónica y certificados de la AGE tiene por objeto establecer el conjunto de criterios comunes asumidos por dicha Administración y sus organismos públicos vinculados o dependientes, en relación con la autenticación y la firma electrónica, que afecta a las relaciones de esta Administración con los ciudadanos y entre sus distintos órganos, según lo previsto en el artículo 24.1 del Real Decreto 1671/2009, de 6 de noviembre, por el que se desarrolla parcialmente la Ley 11/2007, de 22 de junio, de acceso electrónico de los ciudadanos a los Servicios Públicos.
En general, una política de firma electrónica es un documento legal que contiene una serie de normas relativas a la firma electrónica, organizadas alrededor de los conceptos de generación y validación de firma, en un contexto particular (contractual, jurídico, legal,…), definiendo las reglas y obligaciones de todos los actores involucrados en dicho proceso. 
El objetivo de este proceso es determinar la validez de la firma electrónica para una transacción en particular, especificando la información que deberá incluir el firmante en el proceso de generación de la firma, y la información que deberá comprobar el verificador en el proceso de validación de la misma.
Este documento se circunscribe a los certificados previstos en la Ley 11/2007 expedidos para su empleo por la AGE y los organismos públicos vinculados o dependientes de ésta y a los sistemas de firma electrónica basados en certificados recogidos en el artículo 10.1 y 10.2 del Real Decreto 1671/2009.
La política presenta una estructura normalizada del documento electrónico en relación con la creación y validación de firma electrónica, según los estándares técnicos europeos, para facilitar la interoperabilidad de estos documentos, describiendo el alcance y uso de la firma electrónica con la intención de cumplir las condiciones para una transacción concreta en el contexto de las relaciones con los ciudadanos y entre las Administraciones Públicas. 
Este documento propone una política de firma electrónica, que detalla las condiciones generales para la validación de la firma electrónica y una relación de formatos de objetos binarios y ficheros de referencia que deberán ser admitidos por todas las plataformas implicadas en las relaciones electrónicas de la Administración con los ciudadanos y con las Administraciones Públicas.
Esta política marco es de aplicación a toda la Administración General del Estado, y puede convivir junto con otras políticas particulares para una transacción determinada en un contexto concreto, siempre basadas en dicha política marco.
Para su identificación univoca, la política de firma dispondrá de un identificador único que podrá ser un OID en ASN.1 o una URI (URL o URN) en XML. 
Tanto el OID o la URI deberá incluirse obligatoriamente en la firma electrónica, empleando el campo correspondiente para identificar la política marco y la versión con las condiciones generales y específicas de aplicación para su validación, sin perjuicio de lo indicado posteriormente respecto a la posibilidad de acogerse a la modalidad de política implícita. 
La presente política de firma y las políticas de firmas particulares de cada organis o basadas en esta política marco deberán estar disponibles en formato legible, de modo que puedan ser aplicadas en un contexto concreto para cumplir con los requerimientos de creación y validación de firma electrónica.
Las políticas particulares harán referencia al OID y la URL de la política marco de firma electrónica en la que se inscriben, con indicación expresa de la versión. 
En el caso de actualización del presente documento, se identificará el lugar donde un validador puede encontrar las versiones anteriores para verificar una firma electrónica anterior a la política vigente.
En el momento de la firma se deberá incluir la referencia del identificador único de la versión del documento de política de firma electrónica sobre el que se ha basado su implementación, el cual determinará las condiciones que debe cumplir la firma electrónica en un momento determinado.
Para garantizar la fiabilidad de una firma electrónica a lo largo del tiempo, esta deberá ser complementada con la información del estado del certificado asociado en el momento en que la misma se produjo y/o información no repudiable incorporando un sello de tiempo, así como los certificados que conforman la cadena de confianza. 
Esto implica que si queremos tener una firma que pueda ser validada a lo largo del tiempo, la firma electrónica que se genera ha de incluir evidencias de su validez para que no pueda ser repudiada. 
Para este tipo de firmas deberá existir un servicio que mantenga dichas evidencias, y será necesario solicitar la actualización de las firmas antes de que las claves y el material criptográfico asociado sean vulnerables.  
El formato de los documentos electrónicos con firma electrónica avanzada, aplicada mediante los certificados electrónicos admitidos por las Administraciones Públicas y utilizados en el ámbito de las relaciones con o dentro de la Administración Pública, se deberá ajustar a las especificaciones de los estándares europeos relativos a los formatos de firma electrónica.
El Consejo Superior de la Administración Electrónica será la Entidad gestora encargada de publicar y actualizar la relación de las especificaciones relativas a los formatos admitidos por la presente política de firma. 
Opcionalmente, se podrán presentar las solicitudes presencialmente en cualquiera de los lugares y registros establecidos en la normativa reguladora del procedimiento administrativo común.
A estos efectos, los registros de los centros educativos no se consideran incluidos dentro de los lugares y registros establecidos en esta normativa.
La mera presentación de la solicitud lleva implícita la aceptación plena de todas las bases de esta convocatoria, y constituye una manifestación expresa de que la persona solicitante reúne los requisitos exigidos para participar en el procedimiento, así como de que son veraces los datos que consigne en ella.
En caso de que las personas interesadas se opongan la esta consulta, deberán indicarlo en el cuadro correspondiente habilitado en el formulario de inicio y aportar los documentos.
Excepcionalmente, en caso de que alguna circunstancia imposibilite la obtención de los citados datos se podrá solicitar a las personas interesadas la presentación de los documentos correspondientes.
Los alumnos y alumnas que sean candidatos/as al premio deberán merecer un especial reconocimiento por la dedicación y esfuerzo demostrados a lo largo de la etapa en superar sus dificultades, bien de tipo personal, educativas y/o del entorno familiar y sociocultural, por lo que se hacen merecedores de optar a esta modalidad de premios.
El perfil objeto de estos premios se corresponde con el alumnado que procede de entornos socioculturales desfavorecidos o de entornos familiares disfuncionales que supongan desventaja manifiesta cara conseguir finalizar sus estudios o en proceso de superación de enfermedades crónicas o con discapacidades que condicionan su rendimiento escolar, su relación personal y su inserción social.
Las notificaciones de resoluciones y actos administrativos se practicarán preferentemente por medios electrónicos y, en todo caso, cuando las personas interesadas resulten obligadas a recibirlas por esta vía.
Las personas interesadas que no estén obligadas a recibir notificaciones electrónicas podrán decidir y comunicar en cualquier momento que las notificaciones sucesivas se practiquen o dejen de practicar por medios electrónicos.
Este sistema remitirá a las personas interesadas avisos de la puesta a disposición de las notificaciones en la cuenta de correo y/o teléfono móvil que consten en la solicitud.
Estos avisos no tendrán, en ningún caso, efectos de notificación practicada y su falta no impedirá que la notificación sea considerada plenamente válida.
En el caso de personas interesadas obligadas a recibir notificaciones solo por medios electrónicos deberán optar en todo caso por la notificación por medios electrónicos, sin que sea válida ni produzca efectos en el procedimiento una opción diferente.
Las dificultades personales, educativas o del entorno sociofamiliar de la persona candidata, que a juicio del equipo docente dificultaron su desarrollo educativo.
La persistencia del alumno o de la alumna en el logro de las competencias y de los objetivos de la etapa y la valoración del esfuerzo personal para conseguirlos.
La comisión de selección, teniendo en cuenta el informe requerido en el artículo 11 de esta orden, valorará las propuestas presentadas atendiendo a las dificultades personales.
El alumnado ganador debe facilitar la titularidad de una cuenta bancaria con 24 dígitos y declarar sobre la veracidad de los datos relativos a dicha cuenta en que se ingresará, mediante transferencia bancaria, la dotación del premio, según el modelo de anexo II.
Incluirá, igualmente, las referidas ayudas y las sanciones que, como consecuencia de ellas, pudieren imponerse en los correspondientes registros públicos, por lo que la presentación de la solicitud lleva implícita la autorización para el tratamiento necesario de los datos de las personas beneficiarias y la referida publicidad.
En virtud de lo dispuesto en el artículo 4 de la Ley 1/2016, de 18 de enero, de transparencia y buen gobierno, las personas físicas y jurídicas beneficiarias de subvenciones están obligadas a suministrar a la Administración, al organismo o a la entidad de las previstas en el artículo 3.1 de la ley a la que se encuentren vinculadas, previo requerimiento, toda la información necesaria para el cumplimiento por aquella de las obligaciones previstas en el título I de la citada ley.
Sus objetivos son la mejora de los servicios públicos mediante la incorporación de bienes o servicios innovadores; el fomento de la innovación empresarial; y el impulso a la internacionalización de la innovación empleando el mercado público local como cliente de lanzamiento o referencia.
Este proceso se inició el pasado 3 de marzo con la publicación en el Diario Oficial de Galicia de un anuncio con el objetivo de conocer las manifestaciones de interés de empresas interesadas en esta iniciativa. 
A la vista de las manifestaciones recibidas se consideró necesario actualizar algunas de las características de los proyectos incluidas en este primer anuncio y publicar uno nuevo para, sin cambiar su objetivo de apoyar grandes proyectos empresariales de desarrollo experimental que superen los 50 millones de euros, optimizar la inversión pública apoyando también proyectos de un menor tamaño pero con sinergias y complementariedades que permitan conseguir una mayor eficiencia y eficacia de los fondos.
Podrán ser tanto proyectos de investigación industrial como de desarrollo experimental, según las definiciones contenidas en el artículo 2 del Reglamento (UE) nº 651/2014, y a desarrollarse tanto de manera individual como en cooperación con organismos de investigación.
Se valorará especialmente su alto impacto, tanto tecnológico como socioeconómico, en Galicia.
El Informe Innobench surge con el objetivo de que la empresa conozca a través de un procedimiento sistematizado su grado de innovación y posición relativa, pero también con el fin de promover las buenas prácticas y proponer rutas e instrumentos de mejora. 
Por eso tiene, como valor añadido, las Acciones de Mejora para conseguir un desempeño innovador, que se proponen e incluyen en el mismo de manera específica.
El informe también incluye una matriz dinámica de Acciones de Mejora / Ayudas Públicas, en la que se relacionan las acciones a implantar, con recopilación de información sobre ayudas públicas disponibles, elaborando fichas individuales que contemplan las características de las empresas objetivo (sector, tamaño, facturación) y su disponibilidad en el tiempo.
La metodología de generación del Informe InnoBench es fruto del trabajo en colaboración entre el Consorcio de la Zona Franca de Vigo, a través de su servicio de información empresarial ARDÁN, y la Agencia Gallega de Innovación, a los que se suma el trabajo del grupo REDE de la Universidad de Vigo.
En esta sección de la web se presentan los planes y estrategias de la Xunta de Galicia en materia de investigación, desarrollo e innovación, así como enlaces a los planes nacionales y europeos en esta materia.
Esta hoja de ruta de las políticas de innovación de nuestra comunidad es fruto de la exigencia de la Comisión Europea a todas las regiones europeas de definir sus prioridades de gasto en I+D+i para este periodo y de un proceso participativo en el que intervinieron los principales agentes del Sistema Gallego de Innovación coordinados por la Agencia Gallega de Innovación (GAIN).
Desde esta plataforma usted puede interactuar, por medios electrónicos, durante todos los días del año y las 24 horas del día, con los órganos de la Administración general de la Xunta de Galicia para la presentación de solicitudes, escritos y comunicaciones relativas a los diferentes procedimientos administrativos, o para consultar el estado de sus expedientes. 
Además, en esta sede sólo será necesario suministrar datos personales, y se solicitarán sólo los estrictamente imprescindibles, en el caso de realizar algún trámite que requiera de información de estas características. 
En cualquier caso, el tratamiento de los datos de carácter personal que se realice a través de este sitio está sujeto a lo establecido en la Ley Orgánica 15/1999, del 13 de diciembre, de protección de datos de carácter personal.
Es la relación de procedimientos y servicios puestos a disposición de los ciudadanos y de los empleados públicos por la Xunta de Galicia en su sede electrónica, con indicación de plazos de resolución; sentido del silencio; de cuales no pueden ser tramitados electronicamente en todo, o solo en parte; así como la normativa aplicable y los formularios normalizados que deben utilizarse, en cada caso, para iniciar los procedimientos administrativos o solicitar la prestación de servicios.
Recuerde que el contenido de la Guía tiene carácter informativo para quien lo solicite y, por lo tanto, en ningún caso entrañará una interpretación normativa.
El registro electrónico está accesible durante las 24 horas del día, todos los días del año. 
Con todo, hay que tener en cuenta que, a efectos del cómputo de plazos, serán considerados días inhábiles aquellos declarados como tales en el calendario anual de días inhábiles. 
La recepción en un día inhábil se entenderá efectuada el primer día hábil siguiente, considerándose como fecha y hora de entrada las cero horas y un segundo del mismo.
Las sedes electrónicas están reguladas por Ley, por lo que se les exigen determinados requisitos y responsabilidades que no se exigen para las oficinas virtuales. 
En virtud de esto, la sede electrónica tampoco es un portal web al uso, pues, aunque también ofrece contenidos informativos y servicios, estos últimos requieren autenticación en el caso de la sede.
Para poder iniciar un trámite en esta sede debe usted disponer de un certificado electrónico válido. 
Si ya lo tiene, encontrará en el listado de procedimientos una relación de todos aquellos que la Xunta de Galicia tiene disponibles. 
En ese mismo espacio, dispone usted de dos funcionalidades que le serán de utilidad, un buscador que le permitirá localizar aquellos procedimientos que son de su interés –por palabras, áreas temáticas y colectivos- y también una opción para consultar solo aquellos que puede ser iniciados electrónicamente.
Esta consulta es una gestión de carácter nominal, por lo que solo la podrá realizar la misma persona que ha iniciado el procedimiento, mediante autenticación con su correspondiente certificado electrónico.
El procedimiento habitual consiste en realizar la solicitud del certificado a través de la web de la autoridad de certificación correspondiente. 
Posteriormente, el/la solicitante debe acreditar su identidad en alguna de las oficinas habilitadas por la certificadora, donde obtendrá el código de solicitud que le permitirá abordar el último paso, la descarga del certificado vía internet. 
En estos enlaces se facilita la información necesaria para la obtención de los certificados electrónicos de uso más habitual en personas físicas:
El Código de Verificación Electrónica (CVE) sirve para comprobar la autenticidad de las copias en papel de los documentos firmados electrónicamente. 
Los documentos electrónicos firmados por la Xunta contienen un CVE impreso en el lateral de cada página, esto es, un código compuesto por una serie de números y letras que identifican, de forma única, su contenido. 
Aparece, por ejemplo, en las disposiciones, actos o anuncios publicados por la Xunta.
Para cualquier procedimiento que usted inicie en esta sede, la fecha y hora oficiales que debe tener en cuenta a la hora de realizar un trámite no serán las del equipo desde el cual lo efectúa, sino las del registro electrónico que utiliza la sede de la Xunta, es decir, la fecha y hora de esta sede electrónica (que se sincronizan con las del Real Instituto y Observatorio de la Armada – ROA-). 
De la misma forma, para lo relativo al cómputo de plazos será necesario conocer cuales son los días inhábiles de la Comunidad autónoma de Galicia.
En esta página de la sede electrónica encontrará un conjunto de modelos normalizados, con las gestiones más utilizadas por ciudadanos y empresas durante la tramitación administrativa, que podrán ser cubiertos manual o electrónicamente.
Estos modelos normalizados tienen la ventaja de presentar un interfaz homogéneo para todos los procedimientos de la Administración, facilitando a las personas interesadas el aprendizaje de uso del servicio, al tiempo que favorecen la comprensión de la información que se solicita.
